# Rubygems broke build for rvm 1.8.7
# Temporary workaround until version 2.2.1 is released 
# Rubygems commit with the fix is https://github.com/rubygems/rubygems/commit/f8e0f1d5f67cfc4e1966cc1e2db367aebf8a09e4
before_install:
  - gem update --system 2.1.11
  - gem --version
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile: Gemfile
after_install: gem list
script: bundle exec rake spec
notifications:
  email:
    #recipients:
    #  - dev@lists.openshift.redhat.com
  irc:
    - "irc.freenode.org#openshift-dev"
